# Nome do pipeline
name: 'Execução por deploy'

# Regras para disparar o pipeline
# Gatilho de execução manual = workflow_dispatch
on:
  workflow_run:
    workflows: ['Execução manual']
    types:
      - completed

# Trabalhos / Tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:
    # Máquina que o job vai executar
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Passos do script de build
    steps:
      # Clonar o projeto
      - uses: actions/checkout@v4

      # Instalar o node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # Instalar o Yarn
      - name: Instalando o Yarn
        run: npm install -g yarn

      # Instalar as dependências
      - name: Instalando as dependências
        run: yarn

      # Instalar o Playwright
      - name: Instalando o Playwright
        run: yarn playwright install

      # Executar os testes E2E
      - name: Executando os testes E2E
        run: yarn run e2e
